version: '3.8'

services:
  zoekt-mcp-server-ctags:
    build:
      context: .
      dockerfile: Dockerfile.ctags
    image: zoekt-mcp-server:ctags
    container_name: zoekt-mcp-server-ctags
    volumes:
      # Persistent storage for Zoekt index files
      - zoekt-data:/app/.zoekt
      # Directory for cloned repositories
      - zoekt-repos:/app/repos
      # Optional: Mount local directories for development
      # - ./data:/app/.zoekt
      # - ./repos:/app/repos
    environment:
      - ZOEKT_INDEX_DIR=/app/.zoekt
      - PATH=/usr/local/bin:$PATH
    stdin_open: true
    tty: true
    restart: unless-stopped
    
    # Health check including ctags
    healthcheck:
      test: ["CMD", "/usr/local/bin/ctags", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  zoekt-data:
    driver: local
  zoekt-repos:
    driver: local