FROM cgr.dev/chainguard/wolfi-base AS dev
USER root
# Install Chromium with its dependencies
RUN apk update && apk add nodejs npm chromium 

# Set working directory
WORKDIR /app


# Copy package files and install dependencies
# Use PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true to avoid downloading Chromium again
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY index.ts tsconfig.json package.json package-lock.json ./
COPY diagrams /app/diagram
RUN npm install

# Build the TypeScript code
RUN npm run build
FROM cgr.dev/chainguard/wolfi-base

RUN apk update && apk add nodejs

WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY --from=dev /app /app
COPY --from=dev /usr/bin/chromium /usr/bin/chromium
# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
