"""Pytest configuration and fixtures."""

import os
import pytest
import tempfile
from pathlib import Path


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield tmpdir


@pytest.fixture
def sample_python_file(temp_dir):
    """Create a sample Python file for testing."""
    file_path = Path(temp_dir) / "sample.py"
    content = '''
class MyClass:
    """Sample class for testing."""
    
    def __init__(self):
        self.value = 42
    
    def public_method(self):
        """Public method."""
        return self.value
    
    def _private_method(self):
        """Private method."""
        return self.value * 2

def standalone_function(param1, param2):
    """Standalone function."""
    return param1 + param2

GLOBAL_VARIABLE = "test"
'''
    file_path.write_text(content)
    return str(file_path)


@pytest.fixture
def sample_javascript_file(temp_dir):
    """Create a sample JavaScript file for testing."""
    file_path = Path(temp_dir) / "sample.js"
    content = '''
class JavaScriptClass {
    constructor() {
        this.value = 42;
    }
    
    publicMethod() {
        return this.value;
    }
    
    static staticMethod() {
        return "static";
    }
}

function standaloneFunction(param1, param2) {
    return param1 + param2;
}

const arrowFunction = (x) => x * 2;

const GLOBAL_CONSTANT = "test";
'''
    file_path.write_text(content)
    return str(file_path)


@pytest.fixture
def sample_tags_file(temp_dir, sample_python_file):
    """Create a sample tags file."""
    tags_path = Path(temp_dir) / "tags"
    # This would normally be generated by ctags
    # For testing, we'll create a minimal tags file
    content = f'''!_TAG_FILE_FORMAT	2	/extended format/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted/
MyClass	{sample_python_file}	/^class MyClass:/;"	c	line:2
__init__	{sample_python_file}	/^    def __init__(self):/;"	m	line:5	class:MyClass
public_method	{sample_python_file}	/^    def public_method(self):/;"	m	line:8	class:MyClass
_private_method	{sample_python_file}	/^    def _private_method(self):/;"	m	line:12	class:MyClass
standalone_function	{sample_python_file}	/^def standalone_function(param1, param2):/;"	f	line:16
GLOBAL_VARIABLE	{sample_python_file}	/^GLOBAL_VARIABLE = "test"/;"	v	line:20
'''
    tags_path.write_text(content)
    return str(tags_path)