version: '3.8'

services:
  web-content-extractor-mcp:
    build: .
    container_name: web-content-extractor-mcp-server
    volumes:
      # Mount output directory for extracted content
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    # For stdio transport, we need interactive mode
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  output_data: